//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsuranceProduct()
        {
            this.Endorsements = new HashSet<Endorsement>();
            this.Policys = new HashSet<Policy>();
        }
    
        public int ProductId { get; set; }
        public string Products { get; set; }
        public string Createid { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Updateid { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string ProductType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Endorsement> Endorsements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Policy> Policys { get; set; }
    }
}
