//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProjectNew
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sqlpracticeEntities2 : DbContext
    {
        public sqlpracticeEntities2()
            : base("name=sqlpracticeEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Endorsement> Endorsements { get; set; }
        public virtual DbSet<InsuranceProduct> InsuranceProducts { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Policy> Policys { get; set; }
    
        public virtual ObjectResult<prcShowPolicy_Result> prcShowPolicy()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcShowPolicy_Result>("prcShowPolicy");
        }
    
        public virtual ObjectResult<prcShowCustomer_Result> prcShowCustomer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcShowCustomer_Result>("prcShowCustomer");
        }
    
        public virtual ObjectResult<prcShowLogin_Result> prcShowLogin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcShowLogin_Result>("prcShowLogin");
        }
    
        public virtual ObjectResult<prcShowInsuranceProduct_Result> prcShowInsuranceProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcShowInsuranceProduct_Result>("prcShowInsuranceProduct");
        }
    
        
    }
}
